language: go

env:
  global:
    - DOCKER_VERSION=1.10.3-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1

go:
  - 1.6.2

sudo: required

services:
  - docker

before_install:
  - apt-cache madison docker-engine
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - make setup-ci

before_script:
  - docker version
  - docker-compose version
  - make run-containers
  - sleep 10

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

after_success:
  - ./push_to_docker.sh
  - curl -H POST $TEST_FARM_URL
