language: go

go:
  - 1.6.2

sudo: required

services:
  - redis-server
  - elasticsearch
  - docker

before_script:
  - sleep 10

install:
  - make setup-ci

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

after_success:
  - ./push_to_docker.sh
  - curl -H POST $TEST_FARM_URL
