language: go

go:
  - 1.6.2

sudo: required

services:
  - docker

install:
  - make setup-ci

before_script:
  - make run-containers
  - sleep 15
  - curl http://localhost:9123

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

after_success:
  - ./push_to_docker.sh
  - curl -H POST $TEST_FARM_URL
