version: '2'

services:
  redis:
    image: redis:3.2
    ports:
      - "4444:6379"
    networks:
      - mosqnet
  mosquitto:
    image: jllopis/mosquitto:v1.4.9
    volumes:
      - ${PWD}/data:/etc/mosquitto.d
    ports:
      - "1883:1883"
    environment:
      - DOMAIN=example.local
      - PORT=8080
    networks:
      - mosqnet
    depends_on:
      - redis
    labels:
      - "local.example.description=Mosquitto v1.4.9 MQTT server"
  elasticsearch:
    image: elasticsearch:2.3.4
    ports:
      - "9123:9200"
      - "9300:9300"
networks:
  mosqnet:
