---
es:
  host: "localhost"
  port: 9200
  sniff: false
  indexMappings:
    chat: '{ "mappings": { "message": {"_timestamp": { "enabled": true }, "_ttl": { "enabled": true, "default": "2d" }}}}'
    chat2: '{ "mappings": { "message": {"_timestamp": { "enabled": true }, "_ttl": { "enabled": true, "default": "2d" }}}}'
